Feature/CRONAPP-3720 - Utilização de Cookies
technecloud/cronapi-js pull request #191
Opened 2021-05-24 14:53 UTC by alealcronapp

https://cronapp.atlassian.net/browse/CRONAPP-3720

## Problema:
## Melhoria:
Utilização de Cookies no lado cliente e servidor para salvar e recuperar mensagem ( em ambos os lados)
## Solução:
Criação de funções nas camadas cliente e servidor.

# Conflicts:
#	cronapi.js

2021-05-25 11:49 UTC, lincolnminto-cronapp commented on cronapi.js
> +     this.cronapi.util.setCookie = function(key,value) {
Sugestão permitir o cliente definir o Expires. Caso vazio ou inválido (e.x.:"abc") utilizar o valor padrão.

2021-05-25 11:49 UTC, lincolnminto-cronapp commented on cronapi.js
> +      var expiration = new Date();
Utilizar `let` ao invés de `var`

2021-05-25 14:01 UTC, lincolnminto-cronapp commented on cronapi.js
> +    return unescape(cookies.substring(index + halfKey.length, end));
Utilizar `decodeURIComponent()` ao invés de unescape.

2021-05-25 14:06 UTC, lincolnminto-cronapp commented on cronapi.js
> +    this.cronapi.util.getCookie = function(key) {
Sugestão de obtenção de cookie do lado do cliente:

` const value = `; ${document.cookie}`;
  const parts = value.split(`; ${key}=`);
  if (parts.length === 2) return decodeURIComponent(parts.pop().split(';').shift());`

2021-05-25 14:07 UTC, lincolnminto-cronapp requested changes
Sugestões de alteração.

2021-05-25 18:18 UTC, alealcronapp commented on cronapi.js
> +     this.cronapi.util.setCookie = function(key,value) {
Feito!

2021-05-25 18:18 UTC, alealcronapp commented on cronapi.js
> +      var expiration = new Date();
Feito!

2021-05-25 18:49 UTC, alealcronapp commented on cronapi.js
> +      + ";expires="+expiration.toGMTString();
Feito. 
PS: 
Item 4 - Michel pediu pra não adicionar os parâmetros, por conta do usuário low-code, não compreender, na maioria dos casos.

2021-05-25 18:49 UTC, alealcronapp commented on cronapi.js
> +    return unescape(cookies.substring(index + halfKey.length, end));
Feito!

2021-05-26 13:24 UTC, lincolnminto-cronapp commented on i18n/locale_en_us.json
> +  "expirationTimeInSeconds":"Expiration time(s).",
Acredito que o (s) do time é desnecessário. seria uma sugestão que o formato é em segundos? Caso seja colocar time (seconds)

2021-05-26 13:25 UTC, lincolnminto-cronapp commented on i18n/locale_pt_br.json
> +  "expirationTimeInSeconds":"Tempo de expiração(s)",
Acredito que o (s) do expiração é desnecessário. seria uma sugestão que o formato é em segundos? Caso seja colocar expiração (segundos)

2021-05-26 19:32 UTC, drigores approved these changes

2021-05-26 19:32 UTC, merged