CRONAPP-3807 Permitir alterar a câmera utilizada na leitura do QRCode no PWA
technecloud/cronapi-js pull request #232
Opened 2021-09-29 18:09 UTC by paulobalmer-cronapp

**Problema**
Só é possível fazer a leitura utilizando a câmera frontal do dispositivo.

**Solução**
Criada a funcionalidade para alternar entre todas as câmeras disponíveis no dispositivo, tanto diretamente no combobox, como através do botão alternar câmera.

2021-09-29 18:17 UTC, lincolnminto-cronapp commented on cronapi.js
> +    var now = Date.now();
Remover variável não utilizada.

2021-09-29 18:20 UTC, lincolnminto-cronapp commented on cronapi.js
> +    .then(function(stream) {
Ajustar formatação do código.
Utilize lambda sempre que possível.
`navigator.mediaDevices.getUserMedia({audio: false, video: true}).then(stream => {...});`

2021-09-29 18:21 UTC, lincolnminto-cronapp commented on cronapi.js
> +     });
Utilize sempre `const` ou `let` para declaração de variáveis.

2021-09-29 18:24 UTC, lincolnminto-cronapp commented on cronapi.js
> +        for(var i = 0; i < videoInputDevices.length; i ++){
Visto que o índice nunca é utilizado substitua o for por:

`videoInputDevices.map((device=>{...});`
ou
`for(const device of videoInputDevices){...}`

2021-09-29 18:25 UTC, lincolnminto-cronapp commented on cronapi.js
> +        for(var i = 0; i < videoInputDevices.length; i ++){
Garanta que  `videoInputDevices` não é `null` ou `undefined`.
Ex.: `videoInputDevices = videoInputDevices || [];`

2021-09-29 18:26 UTC, lincolnminto-cronapp commented on cronapi.js
> +                                          </div>';
Para declaração de strings com quebra de linha utilize ao invés das aspas simples ou duplas o `meu texto
com quebra
de
linha`

2021-09-29 18:33 UTC, lincolnminto-cronapp commented on cronapi.js
> +        for(var i = 0; i < videoInputDevices.length; i ++){
É necessário repetir o for para o `videoInputDevices` utilizado na linha `3883`

2021-09-29 18:36 UTC, lincolnminto-cronapp commented on cronapi.js
> +                        if (i == 0) {
Use === para evitar coerçao de tipo.
Ex.: Neste caso se `i` for igual a `false` ele entrará no `if`

2021-09-29 18:37 UTC, lincolnminto-cronapp commented on cronapi.js
>          cronappVideoBarCode.find('#cronapiBarCodeCancel').on('click', function() {
Utilize lambda sempre que possível para evitar binds.

2021-09-29 18:38 UTC, lincolnminto-cronapp commented on cronapi.js
> +        cronappVideoBarCode.find('#cronapiBarCodeChangeCam').on('click', function() {
Utilize lambda sempre que possível para evitar binds e problemas de gerenciamento de escopo.

2021-09-29 18:45 UTC, lincolnminto-cronapp requested changes
Verifique por gentileza os pontos citados.

2021-09-29 19:46 UTC, paulobalmer-cronapp commented on cronapi.js
> +    var now = Date.now();
Variável removida

2021-09-29 19:46 UTC, paulobalmer-cronapp commented on cronapi.js
> +    .then(function(stream) {
Ajustado

2021-09-29 19:46 UTC, paulobalmer-cronapp commented on cronapi.js
> +     });
Alterado para let

2021-09-29 19:47 UTC, paulobalmer-cronapp commented on cronapi.js
> +        for(var i = 0; i < videoInputDevices.length; i ++){
Verificação incluída

2021-09-29 19:47 UTC, paulobalmer-cronapp commented on cronapi.js
> +                                          </div>';
alterado o literals

2021-09-29 19:47 UTC, paulobalmer-cronapp commented on cronapi.js
> +        for(var i = 0; i < videoInputDevices.length; i ++){
não era necessário, foi removido.

2021-09-29 19:47 UTC, paulobalmer-cronapp commented on cronapi.js
> +                        if (i == 0) {
alterado conforme solicitado

2021-09-29 19:47 UTC, paulobalmer-cronapp commented on cronapi.js
> +        cronappVideoBarCode.find('#cronapiBarCodeChangeCam').on('click', function() {
altado para utlizar lambda

2021-09-29 20:19 UTC, paulobalmer-cronapp commented
> Verifique por gentileza os pontos citados.

ok

2021-09-29 20:19 UTC, lincolnminto-cronapp commented on cronapi.js
> +        var cameraContainer = `<div style="position: fixed; display: flex; width: 100%; height: 100%; top: 0; left: 0; right: 0; bottom: 0; background-color: \
1.  Não utilize `var`  opte por `const` e `let` ao declarar variáveis.
2. Remova as `\` de quebra de linha já que vc está utilizando agora template literals.

2021-09-29 20:23 UTC, lincolnminto-cronapp commented on cronapi.js
> +        for(var i = 0; i < videoInputDevices.length; i ++){
1.  Não utilize `var`  opte por `const` e `let` ao declarar variáveis.
2. Opte pela versão menos verbosa do loop:
`videoInputDevices.map((device, index)=>{...})`

2021-09-29 20:23 UTC, lincolnminto-cronapp commented on cronapi.js
> +                    var device = videoInputDevices[i];
Não utilize `var`  opte por `const` e `let` ao declarar variáveis.

2021-09-29 20:23 UTC, lincolnminto-cronapp commented on cronapi.js
> +                        var option = document.createElement('option');
Não utilize `var`  opte por `const` e `let` ao declarar variáveis.

2021-09-29 20:24 UTC, lincolnminto-cronapp commented on cronapi.js
> +                   var selectedIndex = $("#videoSource").prop("selectedIndex");
Não utilize `var`  opte por `const` e `let` ao declarar variáveis.

2021-09-29 20:24 UTC, lincolnminto-cronapp commented on cronapi.js
> +                   var itemsInDropDownList = $("#videoSource option").length;
Não utilize `var`  opte por `const` e `let` ao declarar variáveis.

2021-09-29 20:24 UTC, lincolnminto-cronapp requested changes
Ajustes no template e em vars

2021-09-29 20:27 UTC, lincolnminto-cronapp commented on cronapi.js
> +                    var device = videoInputDevices[i];
Dê preferencia a usar uma versão menos verbosa como por exemplo:

`videoInputDevices.map((device, index)=>{...})`

2021-09-29 20:29 UTC, paulobalmer-cronapp commented on cronapi.js
> +                    var device = videoInputDevices[i];
ok

2021-09-29 20:29 UTC, paulobalmer-cronapp commented on cronapi.js
> +                   var itemsInDropDownList = $("#videoSource option").length;
ok

2021-09-29 20:29 UTC, paulobalmer-cronapp commented on cronapi.js
> +                        var option = document.createElement('option');
ok

2021-09-30 11:34 UTC, paulobalmer-cronapp commented
> Ajustes no template e em vars

Ajustes realizados

2021-09-30 11:55 UTC, lincolnminto-cronapp approved these changes

2021-09-30 11:56 UTC, merged